---
name: test
on:
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: retry
        uses: ./
        with:
          command: true
